apiVersion: networking.istio.io/v1beta1  
kind: Gateway  
metadata:  
  name: gateway  
  namespace: istio-system 
  annotations:  
    dns.gardener.cloud/class: garden  
    dns.gardener.cloud/dnsnames: '*.ingress.test.try.shoot.canary.k8s-hana.ondemand.com'  
    dns.gardener.cloud/ttl: '600'  
spec:  
  selector:  
    istio: ingressgateway
  servers:  
  - port:  
      number: 80  
      name: http-productpage  
      protocol: HTTP  
    hosts:
    - "product.ingress.test.try.shoot.canary.k8s-hana.ondemand.com"  
